# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
    - name: Initialize Go module if needed
      run: |
        if [ ! -f go.mod ]; then
          go mod init ste-text-editor
          # Fix import paths in Go files to use module name
          find . -name "*.go" -exec sed -i 's|"ste-text-editor/|"ste-text-editor/|g' {} \;
        fi
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download dependencies
      run: |
        go mod tidy
        go mod download
    - name: Verify dependencies
      run: go mod verify
    - name: Build
      run: go build -v -o STE.exe .
    - name: Test
      run: go test -v ./...
    - name: Run go vet
      run: go vet ./...
    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "The following files are not formatted properly:"
          gofmt -s -l .
          exit 1
        fi
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: STE
        path: STE.exe
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true
    - name: Initialize Go module if needed
      run: |
        if (-not (Test-Path "go.mod")) {
          go mod init ste-text-editor
          # Fix import paths in Go files to use module name
          Get-ChildItem -Path . -Filter "*.go" -Recurse | ForEach-Object {
            (Get-Content $_.FullName) -replace '"ste-text-editor/', '"ste-text-editor/' | Set-Content $_.FullName
          }
        }
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~\AppData\Local\go-build
          ~\go\pkg\mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download dependencies
      run: |
        go mod tidy
        go mod download
    - name: Verify dependencies
      run: go mod verify
    - name: Build for Windows
      run: go build -v -o STEW.exe .
    - name: Test
      run: go test -v ./...
    - name: Upload Windows build artifact
      uses: actions/upload-artifact@v4
      with:
        name: STEW
        path: STEW.exe